name: build-lint-test

on:
  workflow_call: {}

permissions:
  contents: read   # This is required for actions/checkout.

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        args: --timeout=180s
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Run unit tests
      run: make test
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Build image
      run: make docker/build
  lint-charts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Helm
      uses: azure/setup-helm@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        check-latest: true
    - name: Set up chart testing
      uses: helm/chart-testing-action@v2
      with:
        version: 3.8.0
    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --target-branch=${{ github.event.repository.default_branch }})
        if test -n "$changed" ; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi
    - name: Run chart-testing (lint)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct lint --target-branch=${{ github.event.repository.default_branch }}
