name: CI

on:
  push:
    branches:
    - main

env: {}

permissions:
  contents: read   # This is required for actions/checkout.

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        args: --timeout=180s
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Run unit tests
      run: make test
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Build image
      run: make docker/build
  push:
    runs-on: ubuntu-latest
    needs:
    - lint
    - unit-tests
    - build
    steps:
    - name: Generate timestamp
      id: generate-timestamp
      run: echo timestamp=$(date +%Y%m%d%H%M%S) >>$GITHUB_OUTPUT
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Login to Docker
      id: login-docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build image
      run: make docker/build DOCKER_IMAGE=$REGISTRY/$REPOSITORY
      env:
        REGISTRY: docker.io
        REPOSITORY: sageai/ektopistis
    - name: Push image
      run: |
        docker tag $REGISTRY/$REPOSITORY $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      env:
        REGISTRY: docker.io
        REPOSITORY: sageai/ektopistis
        IMAGE_TAG: main-${{ github.sha }}-${{ steps.generate-timestamp.outputs.timestamp }}
